name: turn2draw
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-262.3.beta <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  go_router: ^10.1.2
  logger: ^2.0.2
  nanoid2: ^2.0.1
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  socket_io_client: ^2.0.3+1
  http: ^1.1.0
  firebase_core: ^2.16.0
  firebase_remote_config: ^4.2.6
  firebase_analytics: ^10.5.0
  emojis: ^0.9.9
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/svg_icons/crown.svg
    - assets/svg_icons/pencil.svg
    - assets/svg_icons/stopwatch.svg
    - assets/svg_icons/brush.svg
    - assets/svg_icons/search.svg
  fonts:
    - family: ComingSoon
      fonts:
        - asset: assets/fonts/ComingSoon-Regular.ttf
